[DPE-2131][BUGFIX] lightkube rolebindnig broken (#19)
On namespace creation the follwing error ocurred:

```
FAILED tests/integration/test_registry.py::TestRegistry::test_registry_change_primary_account_1_spark_namespace - lightkube.core.exceptions.ApiError: RoleBinding.rbac.authorization.k8s.io "spark-user-1-role-binding" is invalid: subjects[0].name: Required value
```
* LightKube service fixed
* Tests enabled
* Unittest workflow changes